version: "3"
services:
  traefik:
    image: "traefik:v2.9"
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "81:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
    networks:
      - db_net



  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp
    restart: always
    ports:
      - "7000:80"
    networks:
      - db_net
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mYWORDPRESSUSER
      WORDPRESS_DB_PASSWORD: Password
      WORDPRESS_DB_NAME: wordpressdatabase

    volumes:
      - "./:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-web.rule=Host(`wordpress.docker.localhost`)"
      - "traefik.http.routers.traefik-web.entrypoints=web"

  drupal:
    depends_on:
      - db
    image: drupal:latest
    container_name: dp
    restart: always
    ports:
      - "7080:80"
    environment:
      DRUPAL_DB_HOST: db:3306
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupalpassword
      DRUPAL_DB_NAME: drupaldatabase
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-web.rule=Host(`drupal.docker.localhost`)"
      - "traefik.http.routers.traefik-web.entrypoints=web"
networks:

  db_net:

volumes:

  mysql: {}
